# Generated by Django 3.0.8 on 2020-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20200720_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleitem',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to='article/images/'),
        ),
    ]
