# Generated by Django 3.0.8 on 2020-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_articleitem_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleitem',
            name='banner',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
