# Generated by Django 3.0.8 on 2020-07-20 08:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20200719_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleitem',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
